# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    lanou:
                        password: root
                        roles:
                            - ROLE_USER
                            - ROLE_ADMIN
                            - ROLE_RESP
                            - ROLE_MAGAZ
                    responsable:
                        password: root
                        roles:
                            - ROLE_RESP

                    magasinier:
                        password: root
                        roles:
                            - ROLE_MAGAZ


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login  # quand on submit on declanche l authentication

            logout: ~

    access_control:
        - path : "^/product"
          role : [ROLE_RESP,ROLE_ADMIN]
        - path : "^/addInStock"
          role : [ROLE_RESP,ROLE_ADMIN]
        - path : "^/deleteInStock"
          role : [ROLE_MAGAZ,ROLE_ADMIN]